
name: Call env based reusable workflow

on:
  workflow_dispatch:

jobs:
  deploy_dev:
    name: Deploy to Dev
    uses: ./.github/workflows/reusable_env_action.yml
    with:
      environment: dev
    secrets:
      SOME_PASSWORD: ${{ secrets.SOME_PASSWORD }}
      OTHER_PASSWORD: ${{ secrets.OTHER_PASSWORD }}
      
  deploy_prod:
    name: Deploy to Prod
    needs: deploy_dev
    uses: ./.github/workflows/reusable_env_action.yml
    with:
      environment: prod
    secrets:
      SOME_PASSWORD: ${{ secrets.SOME_PASSWORD }}
      OTHER_PASSWORD: ${{ secrets.OTHER_PASSWORD }}
