name: On PR closed

on:
  pull_request:
    branches:
      - "main"
    types:
      - "closed"

jobs:
  deploy_dev:
    name: Deploy to Dev
    # permissions:
    #   contents: read
    #   pull-requests: write
    uses: ./.github/workflows/reusable_env_action.yml
    with:
        environment: dev
    secrets:
        SOME_PASSWORD: ${{ secrets.SOME_PASSWORD }}
        OTHER_PASSWORD: ${{ secrets.OTHER_PASSWORD }}
