name: Call a reusable workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: ./.github/workflows/wf1.yml@main
  dependant-job:
    runs-on: ubuntu-latest
    needs: call-workflow
    steps:
      - run: echo ${{ needs.call-workflow.outputs.cell }} 
