name: Workflow 1

on:
  workflow_call:
    outputs:
      cell:
        description: "Output cell text"
        value: ${{ jobs.reusable_job_1.outputs.output1 }}

jobs:
  reusable_job_1:
    name: Re-usable job 1
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.cell }}
    steps:
      - id: step1
        run: |
          echo "cell=test" >> $GITHUB_OUTPUT
